[env]
TERM = "screen-256color"

[font]
size = 16.00

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

# Install themes:
# git clone https://github.com/alacritty/alacritty-theme
[general]
import = ["moonfly.toml"]

[window]
opacity = 0.8
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0
