require('config.globals')
require('config.options')
require('config.keymaps')
require('config.autocmd')

require('plugins.blink')
require('config.lsp')

require('plugins.moonfly')
require('plugins.oil')
require('plugins.nvim-treesitter')
require('plugins.presence')
require('plugins.mini-pick')
require('plugins.mini-pairs')
require('plugins.mini-hipatterns')
